// Objective-C API for talking to lanczos Go package.
//   gobind -lang=objc lanczos
//
// File is generated by gobind. Do not edit.

#ifndef __Resizer_H__
#define __Resizer_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * ResizeImage 使用 Lanczos3 调整图像大小并编码为 JPEG。
gomobile 会处理 []byte 和 int 与原生平台类型的转换。
它返回 JPEG 数据的字节切片和一个错误（如果发生）。
 */
FOUNDATION_EXPORT NSData* _Nullable ResizerResizeImage(NSData* _Nullable imgData, long maxSize, long quality, NSError* _Nullable* _Nullable error);

#endif
