
// Objective-C API for talking to the following Go packages
//
//	lanczos
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Resizer_FRAMEWORK_H__
#define __Resizer_FRAMEWORK_H__

#include "Resizer.objc.h"
#include "Universe.objc.h"

#endif
